#BUILD PREREQUISITES
image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - deploy # Deploy services dependent on build output to AWS

# Install dependencies for all tasks
default:
  before_script:
    - apt-get update -q -y
    - apt-get install -q -y python3 python3-pip python3-venv
    - python3 -m venv ~/pyenv
    - source ~/pyenv/bin/activate
    - pip install pipx
    - pipx ensurepath
    - pipx install awscli || true
    - pipx upgrade awscli
    - pipx install aws-sam-cli || true
    - pipx upgrade aws-sam-cli

# CLOUDFORMATION JOBS
