AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM CloudFormation deployment template for Amazon Secrets Manager infrastructure as code (IaC).

Parameters:
  Alias:
    Type: String
    Default: s3rverle5scod3r
  
  #Environment
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - stage
      - prod
  
  #Version, to be supplied in format : {release}.{major}.{minor} (0.0.1)
  Version:
    Type: String
  
Mappings:
  #KMS key per environment for encryption/decryption
  KmsKeyArnToEnvironment:
    # example format : arn:aws:kms:{Region}:{AccountId}:key/{KeyId}
    Environment:
      dev: tbc
      test: tbc 
      stage: tbc
      prod: tbc

Conditions:
  EnvironmentIsProd: !Equals [ !Ref Environment, prod ]
  EnvironmentIsStageOrProd: !Or [ !Equals [ !Ref Environment, stage ], !Equals [ !Ref Environment, prod ] ]
 
Resources:
  RootUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: root-user-secret
      Description: RootUser Secret for an RDS Instance
      KmsKeyId: alias/aws/secretsmanager
      GenerateSecretString:
        PasswordLength: 20
        ExcludeCharacters: "\"@/\\"

  UserASecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: user-a-secret
      Description: User A Secret for an RDS Instance
      KmsKeyId: alias/aws/secretsmanager
      GenerateSecretString:
        SecretStringTemplate: !Sub |
          {
            "username": "userA",
            "engine": "postgres",
            "host": "{DBClusterIdentifier}.{DBClusterId}.{Region}.rds.amazonaws.com",
            "port": "5432",
            "dbClusterIdentifier": "aurora-cluster"
          }
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: " \"#$%&'()+,-./:;<=>?@[\\]^_`{|}~"

    UserBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: user-b-secret
      Description: User B Secret for an RDS Instance
      KmsKeyId: alias/aws/secretsmanager
      GenerateSecretString:
        SecretStringTemplate: !Sub |
          {
            "username": "userB",
            "engine": "postgres",
            "host": "{DBClusterIdentifier}.{DBClusterId}.{Region}.rds.amazonaws.com",
            "port": "5432",
            "dbClusterIdentifier": "aurora-cluster"
          }
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: " \"#$%&'()+,-./:;<=>?@[\\]^_`{|}~"

Outputs:
  RootUserSecretArn:
    Description: "The Arn of the created RootUserSecret"
    Value: !Ref RootUserSecret
    Export:
      Name: RootUserSecretArn
  
  UserASecretArn:
    Description: "The Arn of the created UserASecret"
    Value: !Ref UserASecret
    Export:
      Name: UserASecretArn
  
  UserBSecretArn:
    Description: "The Arn of the created UserBSecret"
    Value: !Ref UserBSecret
    Export:
      Name: UserBSecret